config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
}
   root to: 'homes#top'
   get "home/about" => "homes#about"
   get "searches" => "searches#search"

   resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
   end

   resources :users do
     get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
          get :follows, :followers
        end
     resources :groups, only: [:new, :index, :create, :edit, :update]
  end
 end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @user = @book.user
    if @book_comment.save
      flash[:notice]="Book was successfully created"
      #redirect_to book_path(@book)
    else
      @newbook = Book.new
      render "books/show"
    end
  end

   def destroy
     @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
     @book = Book.find(params[:book_id])
      flash[:notice]="Comment was successfully destroyed."
      #redirect_to book_path(params[:book_id])
   end

private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model:[book, book_comment], remote: true do |f| %>
  <%= f.text_area :comment, rows:'5', class: "form-control" %>
  <%= f.submit "  送信  " %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td class="profile-image">
        <%= link_to user_path(user) do %>
          <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%><br>
           <%= book_comment.user.name %>
          <% end %>
      </td>
      <td class="comment-entry"><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
           <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %>
          <% end %>
        </td>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$("#comment-area").html("<%= j(render "book_comments/index", book: @book, user: @user) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comment-area").html("<%= j(render "book_comments/index", book: @book, user: @user) %>");