config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
}
   root to: 'homes#top'
   get "home/about" => "homes#about"
   get "searches" => "searches#search"

   resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
   end

   resources :users do
     get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
          get :follows, :followers
        end
     resources :groups, only: [:new, :index, :create, :edit, :update]
  end
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: {maximum:20, minimum:2}
  validates :introduction, length: {maximum:50}

  has_many :follower, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :follower, source: :followed
  has_many :followed, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :followed, source: :follower

 #フォローする
  def follow(user_id)
   follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
   follower.find_by(followed_id: user_id).destroy

  end
  # フォロー確認をおこなう
  def following?(user)
   self.followings.include?(user)
  end

   def User.search(search, model, how)
       if model == "user"
         if how == "partical"
           User.where("name LIKE ?", "%#{search}%")
         elsif how == "forward"
           User.where("name LIKE ?", "#{search}%")
         elsif how == "backward"
           User.where("name LIKE?", "%#{search}")
         elsif how == "match"
           User.where("name LIKE?", "#{search}")
         end
       end
   end
   
   has_many :group_users
   has_many :groups, through: :group_users
   
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

   def new
       @book = Book.new
   end

   def index
       @user = current_user
       @users = User.all
       @book = Book.new
       @books = Book.all
       
   end

   def show
       @user = User.find(params[:id])
       @books = @user.books.all
       @book = Book.new
       # bookmodelで定義したscope名　２箇所で使いたいから共通メソッドにした
       show_books
   end

   def search
       @user = User.find(params[:user_id])
       @books = @user.books.all
       @book = Book.new
       if params[:created_at] == ""
           @search_book = "日付を選択してください"
       else
           create_at = params[:created_at]
           @search_book = @books.where!(["created_at LIKE ?", "#{create_at}%"]).count
       end
       show_books
    #   render :show 非同期通信のため消す
   end

   def edit
       @user = User.find(params[:id])
      if @user != current_user
        redirect_to user_path(current_user.id)
      end
   end

   def update
       @user = User.find(params[:id])
     if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
     else
       render :edit
     end
   end

   def follows
     user = User.find(params[:id])
     @users = user.followings
   end

   def followers
     user = User.find(params[:id])
     @users = user.followers
   end

  private

  def show_books   #共通メソッド作成
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @week_books =  @books.created_week

    today = Date.current
    @labels = []
    @week_books.each do |day|
        #差分を求めている。０は配列で日付を取るため
        days = (today-Date.parse(day[0]).to_date).to_i
        @labels << ((days == 0)?  "今日": "#{days}日前")
    end
  end

  def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %> errors prohibited this obj from being saved %>
    <% book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
<% end %>
　　　　　　　　

app/views/users/_follow.html.erb
<table class="table table-sm">
  <thead>
    <th>image</th>
    <th>name</th>
    <th colspan="4"></th>
  </thead>
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.followings.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_userinfo.html.erb
  <table class="table table-user">
  <h2>User info</h2>
    <thead>
      <tr>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpeg" %>
      </tr>
    </thead>
        <tbody>
          <tr>
            <th>Name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
            <tr>
              <th>follows</th>
              <td>
                <%= link_to follows_user_path(user) do %>
                  <%= user.follower.count %>
                <% end %>
              </td>
           </tr>
            <tr>
              <th>followers</th>
              <td>
                <%= link_to followers_user_path(user) do %>
                  <%= user.followed.count %></td>
                <% end %>
              </tr>
            </tr>
              <tr>
                <% if user == current_user %>
                  <th colspan="2">

                <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block' do %>
             <i class="fas fa-user-cog"></i>
             <% end %>
                  </th>
                <% else %>
              </tr>
              <tr>
                <td style="border:none;">
                  <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-primary" %>
                <% else %>
                    <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
                <% end %></td>
              </tr>
            <% end %>
        </tbody>
</table>

app/views/users/edit.html.erb
<main>
 <p id="notice"></p>
   <div class="container">
     <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>

          <%= form_with model: @user, local:true do |f| %>
        	<div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name %>
          </div>

          <div class="form-group">
          <%= f.label :image, "Image" %>
          <%= f.attachment_field :profile_image %>

          <div class="form-group">
          <%= f.label :introduction, "Introduction" %>
          <%= f.text_field :introduction %>
          </div>
          <%= f.submit "Update User", class:"btn btn-secondary" %>

          <% end %>
        </div>
     </div>
   </div>
 </main>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.present? %>
  <%= render 'users/follow', user: @user, users:@users %>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @users.present? %>
  <%= render 'users/follow', user: @user, users:@users %>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/index.html.erb
  <p id="notice"></p>

    <div class="container">
      <div class="row">
          <div class="col-md-3">
                <%= render "users/userinfo", user: @user %>
                <%= render "books/newbook", book: @book %>
                <%= render "users/error_messages", book: @book %>
          </div>
          <div class="col-md-8 offset-md-1">
              <h2>Users</h2>
              <table class="table table-hover table-inverse">
               <thead>
                   <tr>
                     <th>image</th>
                     <th>name</th>
                     <th colspan="3"></th>
                   </tr>
               </thead>
               <tbody>
                 <%= link_to "グループ作成する", new_user_group_path(@user.id) %>
                 |グループ一覧
                  <% @users.each do |user| %>
                    <tr>
                      <td>
                        <%= link_to user_path(user.id) do %>
                          <%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpeg" %>
                        <% end %>
                      </td>
                      <td><%= user.name %></td>
                        <td>
                          <% if current_user != user %>
                            <% if current_user.following?(user) %>
                              <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                            <% else %>
                              <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                            <% end %>
                          <% end %>
                        </td>
                          <td>
                            <%= link_to "Show", user_path(user.id) %>
                          </td>
                    <% end %>
              </tbody>
             </table>
          </div>
      </div>
  </div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<p id="notice"></p>
      <!--ここから下が右側へ-->
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
              <%= render "users/userinfo", user: @user %>
              <%= render "books/newbook", book: @book %>
              <% if @book.errors.any? %>
                <%= @book.errors.count %> errors prohibited this obj from being saved
                <% @book.errors.full_messages.each do |message| %>
                <%= message %>
                <% end %>
                <% end %>
        </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
         <thead>
             <tr>
               <th></th>
               <th>Title</th>
               <th>Opinion</th>
               <th colspan="3"></th>
             </tr>
         </thead>
         <tbody>
           <tr>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
         </tbody>
        </table>
      </div>
    </div>
    <div class = "table_width">
            <table class="table table-bordered">
                 <h3>投稿数の前日比・前週比</h3>
                 <tbody>
                   <tr>
                    <th>今日の投稿数</th>
                    <th>前日の投稿数</th>
                    <th>前日比</th>
                   </tr>
                  </tbody>

                  <tbody>
                   <tr>
                     <td><%= @today_book.count %></td>
                     <td><%= @yesterday_book.count %></td>
                     <td>
                       <% if @yesterday_book.count == 0 %>
                       前日の投稿はありません
                       <% else %>
                       <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
                       <!--to_fは小数点まで表示される。-->
                       <%= (@the_day_before * 100).round %>%
                       <% end %>
                     </td>
                   </tr>
                  </tbody>
            </table>

            <table class="table table-bordered">
                <tbody>
                   <tr>
                    <th>今週の投稿数</th>
                    <th>先週の投稿数</th>
                    <th>前週比</th>
                   </tr>
                </tbody>

                <tbody>
                   <tr>
                     <td><%= @this_week_book.count %></td>
                     <td><%= @last_week_book.count %></td>
                     <td>
                       <% if @last_week_book.count == 0 %>
                       前週の投稿はありません
                       <% else %>
                       <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
                       <!--to_fは小数点まで表示される-->
                       <%= (@the_week_before * 100).round %>%
                       <% end %>
                    </td>
                   </tr>
                </tbody>
            </table>

            <table class="table table-bordered">
              <h3>7日間分の投稿数</h3>
                <tbody>
                  <tr>
                  <% @labels.each do |label| %>
                    <th>
                    <%= label %>
                    </th>
                  <% end %>
                  </tr>
                  <tr>
                    <% @week_books.values.each do |v| %>
                    <td><%= v %></td>
                    <!--1は配列で件数を取るため-->
                    <% end %>
                  </tr>
                </tbody>
            </table>
            <canvas id="myChart" width="300" height="100"></canvas>
          </div>
          <!--local: trueは非同期実装のため外した-->
      <%= form_with url: user_search_path(@user), method: :get do |f| %>
      <%= f.date_field :created_at %>
      <%= f.submit '検索', class: 'btn btn-primary' %>
      <% end %>

        <div id="search_result">
          <% if @search_book.present? %>
            <%= render 'search', search_book: @search_book %>
          <% end %>
        </div>
  </div>

<script>
  $(function() {
    var ctx = document.getElementById("myChart").getContext('2d');

    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: [<% @labels.each do |v| %>"<%= v %>",<% end %>],
        // labelsは横軸。文字列では取り出せない
        datasets: [{  <%# @week_books.each do |day| %>
          label: "投稿した本の数",
          data: <%= @week_books.values %>,
          // dateは縦軸
          backgroundColor: 'white',
          borderColor: 'blue',
          fill: false
        }]
      },
      options: {
        title:  {
          display: true,
          text: "7日間の投稿数の比較",
        },
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true,
              suggestedMin: 0,
              suggestedMax: 10,
            }
          }]
        }
      }
    });
  })
</script>