config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
}
   root to: 'homes#top'
   get "home/about" => "homes#about"
   get "searches" => "searches#search"

   resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
   end

   resources :users do
     get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
          get :follows, :followers
        end
     resources :groups, only: [:new, :index, :create, :edit, :update]
  end
 end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
  	@model = params[:model]
    @how = params[:how]
    if @model == "user"
      @users = User.search(params[:search], @model, @how)
    else
      @books = Book.search(params[:search], @model, @how)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
<div class="search-box">
  <% if user_signed_in? %>
    <%= form_tag(searches_path, method: :get) do %>
      <%= text_field_tag :search %>
      <%= select_tag "model", options_for_select({"User" => "user", "Book"=> "book"}) %>
      <%= select_tag "how", options_for_select({ "部分一致" => "partical", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "match"}) %>
      <%= submit_tag " 検索 ", :name => nil %>
    <% end %>
  <% end %>
</div>

app/views/searches/search.html.erb
<% if @model == "user" %>
  <% if @users.present? %>
    <table class="table table-sm user-index">
      <h2>Users search for " <%= params[:search] %> "</h2>
      <thead>
        <th>image</th>
        <th>name</th>
        <th></th>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", "/users/#{user.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2>Users search for " <%= params[:search] %> "</h2>
      該当のユーザーはいません
    <% end %>
<% elsif @model == "book" %>
  <% if @books.present? %>
    <table class="table book-index">
      <h2>Books search for " <%= params[:search] %> "</h2>
      <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
           </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
  <h2>Books search for " <%= params[:search] %> "</h2>
    該当の本はありません
  <% end %>
<% end %>