config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
}
   root to: 'homes#top'
   get "home/about" => "homes#about"
   get "searches" => "searches#search"

   resources :books do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
   end

   resources :users do
     get "search", to: "users#search"
      resource :relationships, only: [:create, :destroy]
      member do
          get :follows, :followers
        end
     resources :groups, only: [:new, :index, :create, :edit, :update]
  end
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
      <title>Bookers2</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <%= link_to "Home", user_path(current_user), class: 'fas fa-home nav-link text-light'%>
              <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
              <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
              <%= link_to "logout", destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light',method: :delete %>
              <% else %>
              <li><%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %> </li>
              <li><%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %></li>
              <li><%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %></li>
              <% end %>
              <li><%= render "searches/search_form" %></li>
            </ul>
          </div>
        </div>

      </nav>
    </header>

             <%= flash[:notice] %>
             <%= yield %>
    <footer>
      <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>